# GitHub automatically disables scheduled workflows if there has been no
# activity in the repo in the last 60 days. This workflow pushes an empty commit
# every month in order to (hopefully) prevent this
# https://docs.github.com/en/actions/managing-workflow-runs/disabling-and-enabling-a-workflow
name: activity
on:
  schedule:
     # "At 00:00 on day-of-month 1."
     # https://crontab.guru/#0_0_1_*_*
     - cron: "0 0 1 * *"
  workflow_dispatch:
jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: |
          git config user.name "GitHub Actions"
          git config user.email "runneradmin@users.noreply.github.com"
          git pull origin main
      - name: Commit
        run: git commit --allow-empty -m "Activity to enable GitHub Actions worfklows"
      - name: Push
        if: github.repository_owner == 'TileDB-Inc'
        run: git push origin main
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: commit
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: activity
          label: bug
          assignee: shaunrd0,ihnorton,jdblischak
        env:
          TZ: "America/New_York"
