# A temporary workflow to build tiledb-py with Python 3.7 on linux-64.
# Required to support TileDB Cloud UDFs until service agreement expires
name: linux-py37
on:
  schedule:
     # "At minute 23 past hour 0, 6, 12, and 18."
     # https://crontab.guru/#23_0,6,12,18_*_*_*
     - cron: "23 0,6,12,18 * * *"
  workflow_dispatch:
jobs:
  update-recipe:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/TileDB-Inc/tiledb-py-feedstock/tree/build-linux-64-py37
      - name: Clone tiledb-py-feedstock
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/tiledb-py-feedstock
          ref: build-linux-64-py37
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_TILEDB_PY }}
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "runneradmin@users.noreply.github.com"
      - name: Update recipe
        run: |
          wget -O recipe/meta.yaml \
            https://raw.githubusercontent.com/conda-forge/tiledb-py-feedstock/main/recipe/meta.yaml
          git diff
      - name: Commit
        run: |
          git commit -a -m "Update recipe" || echo "nothing to commit"
      - name: Push
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'TileDB-Inc' && github.event_name != 'pull_request'
        run: git push origin build-linux-64-py37
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: update-recipe
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: py37 linux
          label: bug,scheduled,linux-py37
          assignee: shaunrd0,ihnorton,jdblischak
        env:
          TZ: "America/New_York"
