name: tiledb
on:
  schedule:
     - cron: "0 1 * * *" # Every night at 1 AM UTC (8 PM EST; 9 PM EDT)
  workflow_dispatch:
jobs:
  tiledb:
    runs-on: ubuntu-latest
    name: tiledb
    env:
      TZ: "America/New_York"
    steps:
      - name: Clone nightlies CI repo
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/conda-forge-nightly-controller
          path: ci
      - name: Clone feedstock
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/tiledb-feedstock
          ref: main
          path: tiledb-feedstock
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY_TILEDB }}
      - name: Clone source
        uses: actions/checkout@v3
        with:
          repository: TileDB-Inc/TileDB
          ref: dev
          path: TileDB
      - name: Obtain date
        run: bash ci/scripts/obtain-date.sh
      - name: Obtain version
        run: bash ci/scripts/tiledb/obtain-version.sh
      - name: Obtain commit
        run: bash ci/scripts/obtain-commit.sh TileDB
      - name: Pull from upstream feedstock
        run: bash ci/scripts/pull-upstream-feedstock.sh tiledb-feedstock
      - name: Update recipe
        run: bash ci/scripts/tiledb/update-recipe.sh
      - name: Update channels
        run: bash ci/scripts/update-channels.sh tiledb-feedstock
      - name: Add and commit
        run: bash ci/scripts/add-and-commit.sh tiledb-feedstock
      - name: Install conda-smithy with micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: env
          create-args: conda-smithy
          cache-environment: true
      - name: Update conda-smithy
        shell: bash -l {0}
        run: micromamba update --yes conda-smithy
      - name: Rerender feedstock
        shell: bash -l {0}
        run: bash ci/scripts/rerender-feedstock.sh tiledb-feedstock
      - name: Push update to GitHub
        if: github.ref == 'refs/heads/main' && github.repository_owner == 'TileDB-Inc' && github.event_name != 'pull_request'
        run: bash ci/scripts/push-update.sh tiledb-feedstock
  issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: tiledb
    if: ( failure() || cancelled() ) && github.repository_owner == 'TileDB-Inc' && github.event_name == 'schedule'
    steps:
      - uses: actions/checkout@v3
      - name: Open Issue
        uses: TileDB-Inc/github-actions/open-issue@main
        with:
          name: nightly build
          label: nightly-failure
          assignee: shaunrd0,KiterLuc,ihnorton,jdblischak
        env:
          TZ: "America/New_York"
